// 이 파일은 데이터입니다. 첫 줄과 마지막 줄은 그대로 두고 { } 안만 고칩니다.
window.GAYOUNGENE_DATA = window.GAYOUNGENE_DATA || {};
window.GAYOUNGENE_DATA["ui"] =
{
  "_comment": "화면 문구. en은 전부 채워져 있어야 합니다. 다른 언어는 비어 있으면 영어로 대체되고 'Draft translations' 띠가 뜹니다. 언어별 reviewed가 true가 되면 띠가 사라집니다.",
  "languages": [
    { "code": "en", "label": "English", "reviewed": true },
    { "code": "ja", "label": "日本語", "reviewed": false },
    { "code": "vi", "label": "Tiếng Việt", "reviewed": false },
    { "code": "mn", "label": "Монгол", "reviewed": false },
    { "code": "zh-Hans", "label": "简体中文", "reviewed": false },
    { "code": "id", "label": "Bahasa Indonesia", "reviewed": false },
    { "code": "fr", "label": "Français", "reviewed": false }
  ],
  "strings": {
    "en": {
      "siteTitle": "Gayoungene Menu Finder",
      "prototypeBadge": "PROTOTYPE",
      "prototypeNote": "Menu and prices from the owner's list (Sept 2026) · Ingredients and translations still being verified",
      "draftTranslations": "Draft translations · Not reviewed for customer use",
      "nav.menu": "Menu",
      "nav.recommendations": "Recommendations",
      "nav.howToOrder": "How to order",
      "nav.visit": "Visit",
      "finder.kicker": "MENU FINDER",
      "finder.title": "Find food that suits you",
      "finder.description": "Choose ingredients you avoid, your spice level, and the type of food you want.",
      "finder.preferences": "Your food preferences",
      "finder.avoid": "Ingredients you avoid",
      "finder.spice": "Spice level",
      "finder.foodType": "Food type",
      "finder.clear": "Clear filters · Show all dishes",
      "finder.sampleWarning": "Ingredient and spice information is still being verified. Items marked \"Not verified\" have not been checked yet.",
      "ingredient.pork": "Pork",
      "ingredient.beef": "Beef",
      "ingredient.chicken": "Chicken",
      "ingredient.seafood": "Fish & seafood",
      "ingredient.egg": "Egg",
      "ingredient.dairy": "Dairy",
      "spice.any": "Any spice level",
      "spice.0": "Not spicy",
      "spice.1": "Up to mildly spicy",
      "spice.2": "Up to spicy",
      "spice.3": "Very spicy is OK",
      "spiceLabel.0": "Not spicy",
      "spiceLabel.1": "Mildly spicy",
      "spiceLabel.2": "Spicy",
      "spiceLabel.3": "Very spicy",
      "spiceLabel.null": "Not verified",
      "foodType.all": "All dishes",
      "foodType.bunsik": "Tteokbokki & snacks",
      "foodType.fried": "Fried",
      "foodType.meals": "Gimbap & meals",
      "foodType.bingsu": "Shaved ice",
      "foodType.side": "Sides",
      "foodType.drinks": "Drinks",
      "card.photoMissing": "Photo coming soon",
      "detail.draftTranslation": "English text is a draft and has not been reviewed yet.",
      "detail.salesNote": "Note",
      "results.all": "All dishes",
      "results.matching": "Dishes that match your choices",
      "results.count": "{n} dishes",
      "results.countOne": "1 dish",
      "results.noFilters": "No filters selected. Dietary suitability has not been assessed.",
      "results.summaryAvoid": "Ingredients you avoid: {list}",
      "results.summarySpice": "Spice: {level}",
      "results.summaryType": "Food type: {type}",
      "results.excludedUnverified": "Some dishes are excluded because a selected ingredient or spice level is unverified.",
      "results.empty": "No dishes match all your choices.",
      "results.emptyHint": "Change a filter or show all dishes.",
      "card.sample": "Sample",
      "card.menuNo": "Menu No.",
      "card.photoPending": "Photo to be added",
      "card.pricePending": "Price to be confirmed · KRW",
      "card.soldOut": "Sold out",
      "card.needsCheck": "Some ingredients not verified",
      "card.detailsUnverified": "Spice & ingredients not verified",
      "detail.back": "Back to menu",
      "detail.ingredients": "Ingredients",
      "detail.status.contains": "Contains",
      "detail.status.absent_verified": "Verified absent",
      "detail.status.unknown": "Not verified",
      "detail.statusNote": "Verified status covers the full recipe including broth and sauce. Anything not yet checked is shown as Not verified.",
      "detail.spice": "Spice level",
      "detail.matched": "Matches your choices",
      "detail.noFilters": "No filters selected. Dietary suitability has not been assessed.",
      "detail.findInStore": "Find this dish in store",
      "detail.howToOrder": "How to order",
      "detail.notFound": "This dish could not be found. Back to the menu.",
      "find.kicker": "Sample · Menu No.",
      "find.instruction": "Use the number, photo, and Korean name to find the dish.",
      "find.demoNumber": "Demo menu number — not yet matched to the in-store device.",
      "find.back": "Back to details",
      "order.note": "Order and pay at the in-store kiosk or table ordering device.",
      "allergy.note": "Ingredient filters are not an allergy-safety guarantee. Ask staff about allergies and cross-contact.",
      "allergy.notVegan": "No meat does not mean vegan, halal, or allergy-safe.",
      "rec.owner": "Owner's picks",
      "rec.country": "Guest favorites by country",
      "rec.title": "Recommendations",
      "rec.filtersApply": "Your food preferences also apply here.",
      "rec.empty": "No recommendations match your choices.",
      "rec.viewAll": "View all matching dishes",
      "rec.countryPending": "Coming soon. Guest favorites by country will be added after in-store observations are linked to real dishes.",
      "rec.sampleNote": "Sample owner recommendation. Actual selections are not confirmed.",
      "how.kicker": "IN STORE",
      "how.title": "How to order",
      "how.intro": "Use this site to choose, then place your order on the device in the restaurant.",
      "how.pending": "Details to be confirmed before customer use.",
      "visit.kicker": "GAYOUNGENE",
      "visit.title": "Visit",
      "visit.pending": "Address, hours and directions are awaiting confirmation. No live visit information is published in this prototype.",
      "visit.address": "Address",
      "visit.hours": "Hours",
      "visit.map": "Open map",
      "footer.demo": "Education prototype · Ingredient details, spice levels, translations and store information still require review before customer use.",
      "toBeConfirmed": "To be confirmed"
    },
    "ja": {
      "nav.menu": "メニュー",
      "nav.recommendations": "おすすめ",
      "nav.howToOrder": "注文方法",
      "nav.visit": "店舗案内",
      "finder.title": "あなたに合う料理を探す"
    }
  }
}
;
