-- 떡기리 온라인북 v2 — 데이터 창고(Supabase) 테이블
-- Supabase 대시보드 → SQL Editor 에 붙여넣고 Run. 한 번만 실행하면 됩니다.

-- 1) 체크리스트 기록: 날짜 × 매장 × 종류(오픈/마감) 당 한 줄
create table if not exists public.checklist_runs (
  id bigint generated by default as identity primary key,
  run_date date not null,
  store text not null,
  kind text not null check (kind in ('open','close')),
  staff text not null,
  items jsonb not null default '{}'::jsonb,   -- {"0":"2026-09-28T21:03:11Z", ...} 체크한 항목 번호 → 체크 시각
  total int not null default 0,
  done_count int not null default 0,
  note text not null default '',            -- 특이사항 (재고 부족, 기기 이상 등)
  first_completed_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (run_date, store, kind)
);

-- 2) 설정: 매장 목록, 이름 목록 (사장이 앱의 점검표 → 목록 화면에서 등록. 기본값·샘플 없음)
create table if not exists public.settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

-- 3) 잠금(RLS): 익명 키로 읽기·쓰기는 허용, 지우기는 금지
alter table public.checklist_runs enable row level security;
alter table public.settings enable row level security;

drop policy if exists "runs read" on public.checklist_runs;
drop policy if exists "runs insert" on public.checklist_runs;
drop policy if exists "runs update" on public.checklist_runs;
create policy "runs read"   on public.checklist_runs for select to anon using (true);
create policy "runs insert" on public.checklist_runs for insert to anon with check (true);
create policy "runs update" on public.checklist_runs for update to anon using (true) with check (true);

drop policy if exists "settings read" on public.settings;
drop policy if exists "settings insert" on public.settings;
drop policy if exists "settings update" on public.settings;
create policy "settings read"   on public.settings for select to anon using (true);
create policy "settings insert" on public.settings for insert to anon with check (true);
create policy "settings update" on public.settings for update to anon using (true) with check (true);
